language: scala

scala:
  - 2.10.6
  - 2.11.12
jdk:
  - oraclejdk7
env: RUN_MIMA=false
matrix:
  include:
  - scala: 2.12.4
    jdk: oraclejdk8
    env: RUN_MIMA=true

script:
  - sbt clean coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION "test"
  - sbt ++$TRAVIS_SCALA_VERSION "benchmarkJVM/test:compile"
  - sbt ++$TRAVIS_SCALA_VERSION "benchmarkJS/test:compile"
#  - if [ "$RUN_MIMA" == "true" ]; then sbt ++$TRAVIS_SCALA_VERSION "+scalaJsonJVM/mimaReportBinaryIssues" ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
